#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

flag=0

echo

function create_user() {
	useradd -s /bin/false -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://vpnpowerjack.com/debian8x64/source/client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "OpenVPN  : TCP 443 (client config : http://$myip:80/client.ovpn)"
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	echo "---------------------------------"
echo "BIL  USERNAME          EXPIRED "
echo "---------------------------------"
count=1
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
	tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		expired="$(chage -l $username | grep "Account expires" | awk -F": " '{print $2}')"
		if [ $userexpireinseconds -lt $todaystime ] ; then
			printf "%-4s %-15s %-10s %-3s\n" "$count." "$username" "$expired"
			count=$((count+1))
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

clear
echo "        =====================================================
        =====================================================
        #                                                   #
        #     [SELAMAT DATANG DI VPS YUSUF ARDIANSYAH]      #
        #                                                   #
        #           WhatsApp     : 082139743432             #
        #           Telegram     : e-Server                 #
        #           Facebook     : fb.com/t34mh4ck3r        #
        #           Pin-BBM      : yu-suf                   #
        #                                                   #
        #            Copyright © yusuf-ardiansyah           #
        =====================================================

";
PS3='Silahkan ketik angka pilihan anda lalu enter: '
options=("Buat User" "Perbarui User" "Hapus User" "Semua User" "User Belum Kadaluarsa" "User Sudah Kadaluarsa" "Restart Server" "Ganti Password VPS" "Used Data By Users" "Ram Status" "Monitor Multi Login" "Ganti Port OVPN" "Ganti Port Dropbear" "Ganti Port Squid3" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Buat User")
            read -p "Enter username: " uname
            read -p "Enter password: " pass
            read -p "Enter tanggal kadaluarsa (YYYY-MM-DD): " expdate
	    create_user
	    break
            ;;
        "Perbarui User")
            read -p "Enter username yang di perbarui: " uname
            read -p "Enter tanggal kadaluarsa (YYYY-MM-DD): " expdate
            renew_user
            break
            ;;
        "Hapus User")
            read -p "Enter username yang akan di hapus: " uname
            delete_user
            break
            ;;		
		"Semua User")
            user-list
            break
            ;;
		"User Belum Kadaluarsa")
			not_expired_users
			break
			;;
		"User Sudah Kadaluarsa")
			expired_users
			break
			;;		
		"Restart Server")
			reboot
			break
			;;	
		"Ganti Password VPS")
			passwd
			break
			;;
		"Used Data By Users")
			used_data
			break
			;;
		"Ram Status")
		    free -h | grep -v + > /tmp/ramcache
            cat /tmp/ramcache | grep -v "Swap"
            break
              ;;
       "Monitor Multi Login")
               monssh
                break
	          ;;
		"Ganti Port OVPN")	
            echo "Silahkan Ganti Port OpenVPN Anda?"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/server.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			break
			;;
		"Ganti Port Dropbear")	
            echo "Silahkan Ganti Port Dropbear Anda?"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			break
			;;
        "Ganti Port Squid3")	
            echo "Silahkan Ganti Port Squid3 Anda?"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "Squid3 Updated : Port $PORT""
			break
			;;
		"Quit")
		break
		;;
        *) echo invalid option;;
    esac
done
